// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dashboard-variants/PerProjectStack.tsx": () => import("../components/mockups/dashboard-variants/PerProjectStack.tsx"),
  "./components/mockups/dashboard-variants/ProfitCockpit.tsx": () => import("../components/mockups/dashboard-variants/ProfitCockpit.tsx"),
  "./components/mockups/dashboard-variants/SplitConsole.tsx": () => import("../components/mockups/dashboard-variants/SplitConsole.tsx"),
  "./components/mockups/dashboard-variants/TodaysBriefing.tsx": () => import("../components/mockups/dashboard-variants/TodaysBriefing.tsx")
};
